import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

/**
 * Multica's preload exposes a generic `ipcRenderer` pass-through
 * (`window.electron.ipcRenderer`, from @electron-toolkit/preload), so script in
 * the Multica page could otherwise send any channel AO's main process listens
 * on. This builds a small CommonJS preload that runs in the Multica view just
 * before Multica's own preload and limits every outbound IPC method to the
 * channels the Multica bridge serves. Multica's preload looks the methods up on
 * the shared `ipcRenderer` object at call time, so it picks the guards up.
 */
export function multicaIpcJailSource(channels: readonly string[]): string {
	return `"use strict";
// Generated by AO. Runs in the Multica view just before Multica's own preload.
const { ipcRenderer } = require("electron");
const allowed = new Set(${JSON.stringify([...channels].sort())});
for (const method of ["send", "sendSync", "invoke", "postMessage", "sendToHost"]) {
	const original = ipcRenderer[method];
	if (typeof original !== "function") continue;
	ipcRenderer[method] = function (channel, ...args) {
		if (typeof channel !== "string" || !allowed.has(channel)) {
			throw new Error("IPC channel not available in the Multica view: " + String(channel));
		}
		return original.call(ipcRenderer, channel, ...args);
	};
}
`;
}

/** Writes the jail preload under `dir` and returns its path. */
export function writeMulticaIpcJail(dir: string, channels: readonly string[]): string {
	mkdirSync(dir, { recursive: true });
	const file = path.join(dir, "multica-ipc-jail.cjs");
	writeFileSync(file, multicaIpcJailSource(channels), "utf8");
	return file;
}
